=== devkjp/drunken-octo-ironman/Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="family" type="FamilyType"></xs:element>
    <xs:element name="persons" type="PersonsType"></xs:element>
    <xs:element name="relationships" type="RelationshipsType"></xs:element>
    
    <!-- Familientyp -->
    <xs:complexType name="FamilyType">
    	<xs:sequence>
    		<xs:element ref="persons"></xs:element>
    		<xs:element ref="relationships"></xs:element>
    	</xs:sequence>
      <xs:attribute name="name" type="NameType"></xs:attribute>
      <xs:attribute name="description" type="xs:string"></xs:attribute>
    </xs:complexType>
	
	<!-- Aggregation Personen -->
	<xs:complexType name="PersonsType">
		<xs:sequence>
			<xs:element name="person" maxOccurs="unbounded" type="PersonType" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- Personentyp -->
	<xs:complexType name="PersonType">
		<xs:attribute name="id" type="xs:ID" use="required"></xs:attribute>
		<xs:attribute name="firstName"  type="NameType" use="required"></xs:attribute>
		<xs:attribute name="familyName" type="NameType" use="required"></xs:attribute>
		<xs:attribute name="birthDate"  type="xs:date"></xs:attribute>
	</xs:complexType>
	
	<!-- Aggregation Beziehungen -->
	<xs:complexType name="RelationshipsType">
		<xs:sequence >
			<xs:element name="relationship" maxOccurs="unbounded" type="RelationshipType"/> 
		</xs:sequence>
	</xs:complexType>
	
	<!-- Beziehungstyp -->
	<xs:complexType name="RelationshipType">
		<xs:sequence>
			<xs:element name="child" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="id" type="xs:IDREF"></xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="partner1" type="xs:IDREF" use="required"></xs:attribute>
		<xs:attribute name="partner2" type="xs:IDREF" use="required"></xs:attribute>
		<xs:attribute name="date" type="xs:date" use="required"></xs:attribute>
	</xs:complexType>

	<xs:simpleType name="NameType">
    	<xs:restriction base="xs:string">
    		<xs:pattern value="[a-zA-Z][a-zA-Z\-\s]{0,10}"/>
    	</xs:restriction>
    </xs:simpleType>

</xs:schema>

=== devkjp/drunken-octo-ironman/FamilyTree.xml
<?xml version="1.0" encoding="UTF-8"?>

<family xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schema.xsd">
	<persons>
		<person id="p1" 
			firstName="Joseph" 
			familyName="Kennedy" 
			birthDate="1888-09-06"/>
		<person id="p2" 
			firstName="Rose" 
			familyName="Kennedy" 
			birthDate="1890-07-22" />
		<person id="p3" 
			firstName="John" 
			familyName="Kennedy" 
			birthDate="1917-05-29" />
		<person id="p4" 
			firstName="Jacqueline" 
			familyName="Bouvier" 
			birthDate="1929-07-28" />
		<person id="p5" 
			firstName="Rosemary" 
			familyName="Kennedy" 
			birthDate="1918-09-13" />
	</persons>
	
	<relationships>
		<relationship partner1="p1" partner2="p2" date="1908-01-01">
			<child id="p3"></child>
			<child id="p5"></child>
		</relationship>
	</relationships>
</family>
